# Generated by Django 4.2.13 on 2024-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
